### ISSUE TITLE
move permuteddimsview into Base?

### ISSUE THREAD

**Issue by bjarthur** [JuliaImages/juliaimages.github.io#12]
it's a generally useful function.  i know of the desire to keep Base small, but it seems more appropriate there than in Images.

**Comment by timholy** [comment]
Julia-0.6 now exports `PermutedDimsArray`, so maybe we won't even need it.

**Comment by bjarthur** [comment]
yay!  i missed it when i went looking because of the capitalization...

**Comment by bjarthur** [comment]
it's definitely time to deprecate `permuteddimsview`

**Comment by timholy** [comment]
Go for it :smile:
