### ISSUE TITLE
Cropping using Images

### ISSUE THREAD

**Issue by natema** [JuliaImages/juliaimages.github.io#130]
After searching how to crop an image in the docs, I realized that `PaddedView` can be used to do that. 
Perhaps it would be useful to mention in its docstring that PaddedView also works if the output image size is smaller than the input one, effectively implementing a cropping functionality, so that the function would show up when searching for related keywords.

**Comment by johnnychen94** [comment]
I'm not sure if I get your idea correctly, could you provide a demo for that? If available, a [democard](https://juliaimages.org/latest/democards/examples/) could also be helpful for others.

**Comment by timholy** [comment]
The easiest way to crop is indexing: `img[102:418, 208:511]`.

**Comment by natema** [comment]
@johnnychen94 sorry, I agree that my paragraph above is indeed a bit confusing.  
Some details about my specific use case could be helpful.  
I have to pad and crop images of various sizes so that they're all $n\times n$; some image size are greater, some smaller than $n$. 
I was then going to first crop the *extra* entries by indexing, as @timholy suggested, and then padding with `PaddedView`. I then realized that a single call to `PaddedView` would do the job, since it can be used to *anti-*pad (crop) **safely** (i.e. without the assumption that the output range is a subset of the input entries).  
So, I just wish that had found some hints for the latter *trick* in the docs.  
I can propose some lines to add to the docs for it, if you agree, but if you think it is not noteworthy enough, we can close this.

**Comment by timholy** [comment]
No, seems worth documenting. Any changes you want to propose to improve the documentation would be welcome. As @johnnychen94 suggests, a demo card would be particularly awesome, but really anything would help.

**Comment by johnnychen94** [comment]
> I then realized that a single call to PaddedView would do the job

Although the trick seems trivial (PaddedView [restricts/expand its index](https://github.com/JuliaArrays/PaddedViews.jl/blob/1ed7fa0abfc1ac85a0238e0938a81ca0184aa471/src/PaddedViews.jl#L154) if it is explicitly provided), that is something I didn't come up with and I think it worth a demo here.

**Comment by ashwani-rathee** [comment]
I wish to take this up,I am almost done with demo for resize,scaling..should I include cropping in that one only or separately??

**Comment by johnnychen94** [comment]
Good to know that you're interested.

I assume none of them are sufficiently long? These seem to be spatial transformations so might be good to be one demo. You could also find some ideas from https://evizero.github.io/Augmentor.jl/stable/democards/operations/

FYI, I've also introduced PaddedViews in https://juliaimages.org/stable/democards/examples/spatial_transformation/alpha_compositing/#Alpha-Compositing
