### ISSUE TITLE
add Gautam as collaborator

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/juliaimages.github.io#135]
If @mgautam98 is interested in contributing the documentation,  I propose to add him as the collaborator so that he can benefit from the push preview feature. An example of this can be found at https://github.com/JuliaImages/juliaimages.github.io/pull/116

To enlarge the JuliaImages team, we definitely need more advanced contributors and regular developers. I learned a lot when I [updated the quick start page](https://github.com/JuliaImages/juliaimages.github.io/pull/58) last year, I hope this can be a good opportunity for him, too.

@mgautam98 please tell us if you're interested in this

**Comment by mgautam98** [comment]
That would be great. Preview feature is interesting and will be helpful. Yes, I am definitely interested in this.

**Comment by timholy** [comment]
Welcome, @mgautam98, to the docs team!
