### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by pauljurczak** [JuliaImages/juliaimages.github.io#141]
Documentation page https://juliaimages.org/stable/quickstart/# has a broken `Edit on Github` link.

**Comment by pauljurczak** [comment]
Never mind. It works if I select dev version.

**Comment by johnnychen94** [comment]
This is because the folder structure is changed recently in https://github.com/JuliaImages/juliaimages.github.io/pull/125 and hasn't yet push to the stable version.
