### ISSUE TITLE
broken demo: "Cropping, Resizing and Rescaling"

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/juliaimages.github.io#182]
I don't see any code results and a cover is missing for demo: [Cropping, Resizing and Rescaling](https://juliaimages.org/stable/democards/examples/spatial_transformation/SpatialTransformations/#Cropping,-Resizing-and-Rescaling), @ashwani-rathee could you please help fix this?

**Comment by ashwani-rathee** [comment]
@johnnychen94 Sure,though I did test it before pushing it online...can you tell what could be the issue?

**Comment by johnnychen94** [comment]
According to the CI log(e.g., https://github.com/JuliaImages/juliaimages.github.io/runs/2118016729), it seems that we need to add `ImageTransformations` to `Project.toml`.

```julia
┌ Warning: LoadError: ArgumentError: Package ImageTransformations not found in current path:
│ - Run `import Pkg; Pkg.add("ImageTransformations")` to install the ImageTransformations package.
│ 
│ in expression starting at string:1
│ when executing the following code block
│ 
│ ```julia
│ using Images, ImageTransformations, TestImages, OffsetArrays
│ # load an example image
│ img_source = testimage("lighthouse")
│ ```
└ @ DemoCards ~/.julia/packages/DemoCards/oBsQD/src/types/julia.jl:174
┌ Warning: cover file doesn't exists
│   cover_path = "/home/runner/work/juliaimages.github.io/juliaimages.github.io/docs/examples/spatial_transformation/assets/lighthouse.png"
└ @ DemoCards ~/.julia/packages/DemoCards/oBsQD/src/generate.jl:329
```

**Comment by johnnychen94** [comment]
> though I did test it before pushing it online...

This happens when you have `ImageTransformations` installed in your root project. When a package is not specified in `Project.toml` (or more correctly, in `Manifest.toml`) of the project folder, julia will try to find and load it in `DEPOT_PATH` order:

```julia
julia> DEPOT_PATH
3-element Vector{String}:
 "/Users/jc/.julia"
 "/Applications/Julia-1.6.app/Contents/Resources/julia/local/share/julia"
 "/Applications/Julia-1.6.app/Contents/Resources/julia/share/julia"
```

In my case, Julia will finds this package in `/Users/jc/.julia/environments/v1.6/Manifest.toml`. However, every build in CI is a [clean setup](https://github.com/JuliaImages/juliaimages.github.io/blob/4749786007ffd4553ca265bd6115126e3a1047b0/.github/workflows/docs.yml#L36-L41), so Julia complains about it.

**Comment by ashwani-rathee** [comment]
@johnnychen94 Okay,I'll just update it with ImageTransformations addititon,Should I create another PR for that or can the merged PR can be reverted and opened again?

**Comment by johnnychen94** [comment]
When a PR is merged, it can only be reverted. So yeah please create a new PR.
