### ISSUE TITLE
Beginner questions on displaying images

### ISSUE THREAD

**Issue by JGameCreation** [JuliaImages/juliaimages.github.io#186]
Hi,

I'm new to Julia and JuliaImages and have to very simple questions:
1.  How can I display images when I use VS Code (on Windows)? In Juno it's shown in the plots window but in VS Code it seems like it's shown nowhere.
2. When the function in the last line returns an image it is automatically displayed but how do I show an image earlier in my program?

Thanks!

**Comment by juliohm** [comment]
Hi @JGameCreation please direct these user questions to the forums like Zulip and Discourse.

These questions aren't related to the Images.jl project specifically. You can always call `display(obj)` on any object in Julia to see a visual representation.
