### ISSUE TITLE
Initial experience - just want to display an image!!

### ISSUE THREAD

**Issue by dan-at-awesome-tech** [JuliaImages/juliaimages.github.io#190]
Hi, complete Julia newbie here.
Checking https://juliaimages.org/stable/tutorials/quickstart/ and dismayed to find no images shown and a cryptic "Don't worry if you don't get the "image" result, that's expected and you'll learn how to automatically display an image later in JuliaImages."
The function of showing something should be a mandatory first activity for an images package. Please restructure content / do whatever you have to do, to make the ability to show image results immediate.
Image capabilities is going to be one of the first things people check as they consider taking up Julia, so showing images fast and easily will help accelerate the whole Julia ecosystem.
Cheers

**Comment by johnnychen94** [comment]
Will it be clearer if we provide a link to https://juliaimages.org/stable/install/#sec_visualization?

**Comment by ashwani-rathee** [comment]
@dan-at-awesome-tech Hey there, I am assuming you're a scikit-image user. scikit-image has a tiny/quick `Getting started` snippet on the landing page https://scikit-image.org/ to show images from terminal. https://juliaimages.org/stable/ landing page gives a brief description about the org and then points to `Getting Started` which shows how to load, and show images in Ijulia/jupyter notebook. It won't be too bad a idea to use ImageView in getting started/tutorial to show images from REPL/terminal which is where any new user starts.

**Comment by xgupta** [comment]
>a cryptic "Don't worry if you don't get the "image" result, that's expected and you'll learn how to automatically display an image later in JuliaImages."

This line should be displayed before because the user didn't get the image when run `img = rand(4, 3)` so spending their time on the internet why quickstart show the image but not their Julia terminal.
