### ISSUE TITLE
Tell user to run `using Images` in quickstart.md

### ISSUE THREAD

**Issue by xgupta** [JuliaImages/juliaimages.github.io#194]
User get confuse why running `Gray(0.0) # black` giveing error in [quickstart.md](https://juliaimages.org/latest/tutorials/quickstart/#Array-elements-are-pixels-(and-vice-versa)).

See screenshot :
![junliaimage](https://user-images.githubusercontent.com/72094336/119926729-88239e00-bf95-11eb-937b-3284497abeee.png)

https://juliaimages.org/latest/tutorials/quickstart/#Array-elements-are-pixels-(and-vice-versa)

Might be obvious for others but good to mention

**Comment by johnnychen94** [comment]
A good change for me.

Previously, I thought users will run https://juliaimages.org/stable/install/ first so I didn't add this.
