### ISSUE TITLE
houseclean: compress the git history and previews

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/juliaimages.github.io#211]
With more commits in and the preview feature switched on, this repo history now becomes quite large and actually hurts the contributor experiences:

```julia
➜ git clone git@github.com:JuliaImages/juliaimages.github.io.git
Cloning into 'juliaimages.github.io'...
Connection to github.com port 22 [tcp/ssh] succeeded!
remote: Enumerating objects: 9613, done.
remote: Counting objects: 100% (1229/1229), done.
remote: Compressing objects: 100% (332/332), done.
remote: Total 9613 (delta 558), reused 1191 (delta 527), pack-reused 8384
Receiving objects: 100% (9613/9613), 158.91 MiB | 3.11 MiB/s, done.
Resolving deltas: 100% (4853/4853), done.
```

while the git history for our source branch is quite small:

```julia
➜ git clone git@github.com:JuliaImages/juliaimages.github.io.git --branch source --depth 99999
Cloning into 'juliaimages.github.io'...
Connection to github.com port 22 [tcp/ssh] succeeded!
remote: Enumerating objects: 1076, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 1076 (delta 15), reused 31 (delta 13), pack-reused 1040
Receiving objects: 100% (1076/1076), 5.83 MiB | 1.81 MiB/s, done.
Resolving deltas: 100% (590/590), done.
```

This is due to the continuous push from our Documenter CI to the `master` branch's `dev` and `previews` folders

```julia
➜ du -sh *
4.0K	CNAME
 47M	dev
4.0K	index.html
942M	previews
8.5M	v0.19.3
8.5M	v0.20.0
8.5M	v0.20.1
 11M	v0.21.0
 11M	v0.21.1
 12M	v0.22.0
 29M	v0.22.4
 29M	v0.23.1
 30M	v0.23.3
4.0K	versions.js
```

There are two options:

1. separate our source codes and generated codes into two repos. This can be done by moving our source codes branch `source` to another repo, and pushing from there to this repo: `Documenter.deploydocs` supports push to other repo via `repo` keyword.
2. rebase, force push, and clean our `master` branch history(the generated codes). We need to do this once and then let the `forcepush=force` keyword of `Documenter.deploydocs` to do the future commits.

The large `previews` folder usage can be perhaps solved by another CI setup: https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#gh-pages-Branch that cleans the previews from the git history when PR is merged/closed.

I prefer the second option. Any thoughts?

**Comment by timholy** [comment]
You know more than I, so I'd be supportive of whatever you think best. Just to double-check, since all commits are made on `source` this shouldn't have any impact on developers (other than positive), right?

**Comment by johnnychen94** [comment]
Correct, it won't affect normal development experiences. The only thing that might be worth noting is that PR previews will be deleted and thus preview URL will become 404 when that PR is merged.

After option 2, now the repo size is ~4x smaller in my fork: `44.83 MiB`(fork) compared to `158.91 MiB` (origin)

```console
➜ git clone git@github.com:johnnychen94/juliaimages.github.io.git
Cloning into 'juliaimages.github.io'...
Connection to github.com port 22 [tcp/ssh] succeeded!
remote: Enumerating objects: 1875, done.
remote: Counting objects: 100% (465/465), done.
remote: Compressing objects: 100% (279/279), done.
remote: Total 1875 (delta 268), reused 274 (delta 157), pack-reused 1410
Receiving objects: 100% (1875/1875), 44.83 MiB | 3.22 MiB/s, done.
Resolving deltas: 100% (906/906), done.
```

If we want to further reduce the repo size, we should then separate the current repo into two repos. But I'm satisfied with <100MiB, this issue is for future proof to slow down the storage increase speed.

**Comment by timholy** [comment]
Sounds good to me, I'm happy if you are.
