### ISSUE TITLE
Comparision table in the docs needs to be updated

### ISSUE THREAD

**Issue by tosalonijain** [JuliaImages/juliaimages.github.io#22]
![issuejulia2](https://user-images.githubusercontent.com/31576507/33977013-b7d87918-e0be-11e7-8dcd-b74ae4ca0ced.png)

There had been considerable works on image segmentation algorithms in JuliaImages. Though the segmentation section under "JuliaImages" column is still not updated accordingly.

**Comment by tosalonijain** [comment]
@timholy can I work on this and make the changes??

**Comment by SimonDanisch** [comment]
I'm sure everyone would be very happy if you open a PR with the changes! ;)

**Comment by timholy** [comment]
Yes, that would be wonderful! I am pretty swamped, and most of my coding attention is on the julia 1.0 release right now.
