### ISSUE TITLE
Having trouble with imresize and pixel art

### ISSUE THREAD

**Issue by davidalencia** [JuliaImages/juliaimages.github.io#247]
I have a problem increasing the size of a pixel art image (matrix). I have a 3x3 matrix, and I use imresize to increase it to 200x200 but it doesn't keep the pixel aesthetic. I have tried using different arguments in `method` but i can't find a way to keep the pixels defined.

``` julia
finding = RGB.([0 0 0;1 0 1;0 0 0])
```
![image](https://user-images.githubusercontent.com/20330355/170326274-0d83d5e9-7a00-4249-a9d0-572dfaf298f4.png)
``` julia
imresize(finding, (200,200))
```

![image](https://user-images.githubusercontent.com/20330355/170326431-52c0b51c-5be3-4a16-b5c7-08da11e3e0ad.png)

**Comment by rubal501** [comment]
imresize(finding, (200, 200), method=BSpline(Constant()))
