### ISSUE TITLE
Comparison to OpenCV/cv2

### ISSUE THREAD

**Issue by jariji** [JuliaImages/juliaimages.github.io#258]
I am trying to port some Python code to Julia. I saw there is a nice [comparison](https://juliaimages.org/latest/api_comparison/) with some frameworks. Since the code I'm porting uses `cv2`, it would be helpful to have a comparison to that as well.

For instance I am going to be looking for 

```
cv2.findContours
cv2.contourArea
cv2.boxPoints
cv2.minAreaRect
cv2.threshold
cv2.resize
```

**Comment by ashwani-rathee** [comment]
Let's see:
- findContours/contourArea/boxpoints/minAreaRect: https://juliaimages.org/latest/examples/contours/contour_detection/ this might be of interest, and these types of methods are provided by ImageComponentAnalysis.jl 
- Threshold: https://github.com/JuliaImages/ImageBinarization.jl
- Resize: https://github.com/JuliaImages/ImageTransformations.jl

**Comment by ashwani-rathee** [comment]
We need to update the comparison page and list of packages we serve.

**Comment by ashwani-rathee** [comment]
Issue #230 and #244
