### ISSUE TITLE
Documentation not updating

### ISSUE THREAD

**Issue by Evizero** [JuliaImages/juliaimages.github.io#44]
Travis says `[ Info: skipping docs deployment.`. Any ideas why? Could it be the one failing doctest that print the testimage download?

https://travis-ci.org/JuliaImages/juliaimages.github.io/builds/478700837

**Comment by timholy** [comment]
https://github.com/JuliaImages/juliaimages.github.io/commit/98bf07589024f9fe43139e70dc2bed75da8c054e#commitcomment-31781807

I've been swamped with other things and haven't looked into reverting that commit and its neighbor.

**Comment by Evizero** [comment]
I have cherrypit that commit earlier today (i.e. its gone and I forcepushed)

**Comment by timholy** [comment]
I belatedly noticed that. Many thanks!!

> maybe the debug environment variable?

I put that in to try to debug deployment, but I think more recent versions of Documenter don't require that anymore. So it could probably be deleted.

Seems like there are many unresolved links. Do you get that when you build locally?

**Comment by johnnychen94** [comment]
The "Skipping deploy" comes from deprecated `deploydocs` keywords: `julia` and `osname`

see: 
https://github.com/JuliaDocs/Documenter.jl/blob/c59fe92f880e7acfbf2610fed0c70dc364e4c3a0/src/Documenter.jl#L500-L513
