### ISSUE TITLE
Broken links in https://github.com/JuliaImages/juliaimages.github.io/blob/source/docs/src/quickstart.md

### ISSUE THREAD

**Issue by allomorphy** [JuliaImages/juliaimages.github.io#53]
Just a heads up, that all the links in this page except for the second
 one are 404. Of course, it could be that I am seeing an artefact from looking directly at the sources.
 
Best wishes 
Eric

**Comment by johnnychen94** [comment]
thanks for the report

If you click from source code, it would jump to 
`https://github.com/JuliaImages/juliaimages.github.io/blob/source/docs/src/@ref` This behavior is expected. These `@ref`s will be translated to the real cross-reference links when generated by `Documenter.jl`.

https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@ref-link-1

**Comment by timholy** [comment]
They work for me on https://juliaimages.org/latest/quickstart/. If they don't for you, please re-open.
