### ISSUE TITLE
ERROR: What wrong ?

### ISSUE THREAD

**Issue by programistawpf** [JuliaImages/juliaimages.github.io#8]
What wrong , all was copy from docs.
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of DataFrames...
INFO: Updating cache of DataFrames...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using Images, Unitful, AxisArrays

julia> using Unitful: mm, s

julia>

julia> img = AxisArray(rand(256, 256, 100, 50), (:x, :y, :z, :time), (0.4mm, 0.4mm, 1mm, 2s))
ERROR: ArgumentError: the length of each axis must match the corresponding size of data
 in AxisArrays.AxisArray{T,N,D,Ax}(::Array{Float64,4}, ::Tuple{AxisArrays.Axis{:x,StepRange{Quantity{Float64, Dimensions
:{?}, Units:{mm}},Quantity{Float64, Dimensions:{?}, Units:{mm}}}},AxisArrays.Axis{:y,StepRange{Quantity{Float64, Dimensi
ons:{?}, Units:{mm}},Quantity{Float64, Dimensions:{?}, Units:{mm}}}},AxisArrays.Axis{:z,StepRange{Quantity{Int64, Dimens
ions:{?}, Units:{mm}},Quantity{Int64, Dimensions:{?}, Units:{mm}}}},AxisArrays.Axis{:time,StepRange{Quantity{Int64, Dime
nsions:{?}, Units:{s}},Quantity{Int64, Dimensions:{?}, Units:{s}}}}}) at C:\Users\PC\.julia\v0.5\AxisArrays\src\core.jl:
178
 in AxisArrays.AxisArray{T,N,D,Ax}(::Array{Float64,4}, ::AxisArrays.Axis{:x,StepRange{Quantity{Float64, Dimensions:{?},
Units:{mm}},Quantity{Float64, Dimensions:{?}, Units:{mm}}}}, ::AxisArrays.Axis{:y,StepRange{Quantity{Float64, Dimensions
:{?}, Units:{mm}},Quantity{Float64, Dimensions:{?}, Units:{mm}}}}, ::AxisArrays.Axis{:z,StepRange{Quantity{Int64, Dimens
ions:{?}, Units:{mm}},Quantity{Int64, Dimensions:{?}, Units:{mm}}}}, ::AxisArrays.Axis{:time,StepRange{Quantity{Int64, D
imensions:{?}, Units:{s}},Quantity{Int64, Dimensions:{?}, Units:{s}}}}) at C:\Users\PC\.julia\v0.5\AxisArrays\src\core.j
l:176
 in AxisArrays.AxisArray{T,N,D,Ax}(::Array{Float64,4}, ::Tuple{Symbol,Symbol,Symbol,Symbol}, ::Tuple{Quantity{Float64, D
imensions:{?}, Units:{mm}},Quantity{Float64, Dimensions:{?}, Units:{mm}},Quantity{Int64, Dimensions:{?}, Units:{mm}},Qua
ntity{Int64, Dimensions:{?}, Units:{s}}}) at C:\Users\PC\.julia\v0.5\AxisArrays\src\core.jl:207

Paul

**Comment by timholy** [comment]
Hmm, when I wrote that I evidently had some unfinished local changes to Unitful. I finished those up and submitted them here: https://github.com/ajkeller34/Unitful.jl/pull/51. When a new release gets tagged, this should just start magically working for you.

**Comment by timholy** [comment]
Closed by https://github.com/ajkeller34/Unitful.jl/pull/51, though for now you'll have to `Pkg.checkout("Unitful")` to get the fix.
